export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const SET_USER_SAVED_DEVELOPERS = 'SET_USER_SAVED_DEVELOPERS';
export const SET_USER_SAVED_JOBS = 'SET_USER_SAVED_JOBS';